/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyFrameworkRouteImport } from './routes/weekly-framework'
import { Route as SyllabusOverviewRouteImport } from './routes/syllabus-overview'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as StartupResidencyRouteImport } from './routes/startup-residency'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProgramGovernanceRouteImport } from './routes/program-governance'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as MentorFrameworkRouteImport } from './routes/mentor-framework'
import { Route as IndustryReadinessRouteImport } from './routes/industry-readiness'
import { Route as IndustryPartnerRouteImport } from './routes/industry-partner'
import { Route as FounderReviewRouteImport } from './routes/founder-review'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as CreditMappingRouteImport } from './routes/credit-mapping'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CohortPlannerRouteImport } from './routes/cohort-planner'
import { Route as CareerOutcomesRouteImport } from './routes/career-outcomes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const WeeklyFrameworkRoute = WeeklyFrameworkRouteImport.update({
  id: '/weekly-framework',
  path: '/weekly-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusOverviewRoute = SyllabusOverviewRouteImport.update({
  id: '/syllabus-overview',
  path: '/syllabus-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupResidencyRoute = StartupResidencyRouteImport.update({
  id: '/startup-residency',
  path: '/startup-residency',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramGovernanceRoute = ProgramGovernanceRouteImport.update({
  id: '/program-governance',
  path: '/program-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorFrameworkRoute = MentorFrameworkRouteImport.update({
  id: '/mentor-framework',
  path: '/mentor-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryReadinessRoute = IndustryReadinessRouteImport.update({
  id: '/industry-readiness',
  path: '/industry-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPartnerRoute = IndustryPartnerRouteImport.update({
  id: '/industry-partner',
  path: '/industry-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderReviewRoute = FounderReviewRouteImport.update({
  id: '/founder-review',
  path: '/founder-review',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditMappingRoute = CreditMappingRouteImport.update({
  id: '/credit-mapping',
  path: '/credit-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortPlannerRoute = CohortPlannerRouteImport.update({
  id: '/cohort-planner',
  path: '/cohort-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerOutcomesRoute = CareerOutcomesRouteImport.update({
  id: '/career-outcomes',
  path: '/career-outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/evaluation': typeof EvaluationRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/evaluation': typeof EvaluationRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/evaluation': typeof EvaluationRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/evaluation'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/evaluation'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/evaluation'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CareerOutcomesRoute: typeof CareerOutcomesRoute
  CohortPlannerRoute: typeof CohortPlannerRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CreditMappingRoute: typeof CreditMappingRoute
  EvaluationRoute: typeof EvaluationRoute
  FounderReviewRoute: typeof FounderReviewRoute
  IndustryPartnerRoute: typeof IndustryPartnerRoute
  IndustryReadinessRoute: typeof IndustryReadinessRoute
  MentorFrameworkRoute: typeof MentorFrameworkRoute
  OutcomesRoute: typeof OutcomesRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProgramGovernanceRoute: typeof ProgramGovernanceRoute
  RoadmapRoute: typeof RoadmapRoute
  StartupResidencyRoute: typeof StartupResidencyRoute
  SyllabusRoute: typeof SyllabusRoute
  SyllabusOverviewRoute: typeof SyllabusOverviewRoute
  WeeklyFrameworkRoute: typeof WeeklyFrameworkRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-framework': {
      id: '/weekly-framework'
      path: '/weekly-framework'
      fullPath: '/weekly-framework'
      preLoaderRoute: typeof WeeklyFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus-overview': {
      id: '/syllabus-overview'
      path: '/syllabus-overview'
      fullPath: '/syllabus-overview'
      preLoaderRoute: typeof SyllabusOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-residency': {
      id: '/startup-residency'
      path: '/startup-residency'
      fullPath: '/startup-residency'
      preLoaderRoute: typeof StartupResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-governance': {
      id: '/program-governance'
      path: '/program-governance'
      fullPath: '/program-governance'
      preLoaderRoute: typeof ProgramGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-framework': {
      id: '/mentor-framework'
      path: '/mentor-framework'
      fullPath: '/mentor-framework'
      preLoaderRoute: typeof MentorFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-readiness': {
      id: '/industry-readiness'
      path: '/industry-readiness'
      fullPath: '/industry-readiness'
      preLoaderRoute: typeof IndustryReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-partner': {
      id: '/industry-partner'
      path: '/industry-partner'
      fullPath: '/industry-partner'
      preLoaderRoute: typeof IndustryPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-review': {
      id: '/founder-review'
      path: '/founder-review'
      fullPath: '/founder-review'
      preLoaderRoute: typeof FounderReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-mapping': {
      id: '/credit-mapping'
      path: '/credit-mapping'
      fullPath: '/credit-mapping'
      preLoaderRoute: typeof CreditMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-planner': {
      id: '/cohort-planner'
      path: '/cohort-planner'
      fullPath: '/cohort-planner'
      preLoaderRoute: typeof CohortPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-outcomes': {
      id: '/career-outcomes'
      path: '/career-outcomes'
      fullPath: '/career-outcomes'
      preLoaderRoute: typeof CareerOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CareerOutcomesRoute: CareerOutcomesRoute,
  CohortPlannerRoute: CohortPlannerRoute,
  CommandCenterRoute: CommandCenterRoute,
  CreditMappingRoute: CreditMappingRoute,
  EvaluationRoute: EvaluationRoute,
  FounderReviewRoute: FounderReviewRoute,
  IndustryPartnerRoute: IndustryPartnerRoute,
  IndustryReadinessRoute: IndustryReadinessRoute,
  MentorFrameworkRoute: MentorFrameworkRoute,
  OutcomesRoute: OutcomesRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProgramGovernanceRoute: ProgramGovernanceRoute,
  RoadmapRoute: RoadmapRoute,
  StartupResidencyRoute: StartupResidencyRoute,
  SyllabusRoute: SyllabusRoute,
  SyllabusOverviewRoute: SyllabusOverviewRoute,
  WeeklyFrameworkRoute: WeeklyFrameworkRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
